CREATE TABLE IF NOT EXISTS
    PASSENGERS ( ID numeric , NAME VARCHAR(50), COUNTRY VARCHAR(50));

# INSERT INTO PASSENGERS (ID, NAME, COUNTRY) VALUES (1, 'Jim', 'US');
# INSERT INTO PASSENGERS (ID, NAME, COUNTRY) VALUES (2, 'Jack', 'UK');
INSERT INTO PASSENGERS (ID, NAME, COUNTRY) VALUES (3, 'Jill', 'AU');